CREATE TABLE `account_collect_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(255) DEFAULT NULL COMMENT '服务名称',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `product_id` VARCHAR(255) DEFAULT NULL COMMENT '产品ID',
  `account_id` VARCHAR(255) DEFAULT NULL COMMENT '账户ID',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账户收藏实体类';


CREATE TABLE `account_product_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(255) DEFAULT NULL COMMENT '服务名称',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `product_brief` VARCHAR(255) DEFAULT NULL COMMENT '服务简介',
  `product_describe` VARCHAR(255) DEFAULT NULL COMMENT '服务描述',
  `sub_name` VARCHAR(255) DEFAULT NULL COMMENT '副标题',
  `banner` VARCHAR(255) DEFAULT NULL COMMENT '背景图',
  `short_name` VARCHAR(255) DEFAULT NULL COMMENT '简称',
  `view_count` INT DEFAULT NULL COMMENT '查看次数',
  `link_path` VARCHAR(255) DEFAULT NULL COMMENT '服务链接',
  `prod_status` VARCHAR(255) DEFAULT NULL COMMENT '服务状态 (正常normal|内测internal|公测public)',
  `has_inner` INT COMMENT '是否内置链接 (内置1|正常0)',
  `identity_status` VARCHAR(255) DEFAULT NULL COMMENT '标识状态 (0启用|1禁用)',
  `product_type_id` VARCHAR(255) DEFAULT NULL COMMENT '所属类型id',
  `link_open_type` VARCHAR(255) DEFAULT NULL COMMENT '所属类型id',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账户产品项实体类';


CREATE TABLE `account_sign` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `has_day_sign` INT DEFAULT NULL COMMENT '今天是否已签到',
  `sign_day_count` INT DEFAULT NULL COMMENT '签到天数',
  `growth_value` INT DEFAULT NULL COMMENT '成长值',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账号签到实体类';


CREATE TABLE `app_screen` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `icon` VARCHAR(255) DEFAULT NULL COMMENT '图标',
  `title` VARCHAR(255) DEFAULT NULL COMMENT '标题',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `screen_index` INT DEFAULT NULL COMMENT '排序',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用屏幕实体类';


CREATE TABLE `app_screen_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `screen_id` VARCHAR(255) DEFAULT NULL COMMENT '场景ID',
  `item_id` VARCHAR(255) DEFAULT NULL COMMENT '项ID',
  `user_id` VARCHAR(255) DEFAULT NULL COMMENT '用户ID',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='场景应用产品项实体类';


CREATE TABLE `cloud_account_audit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `account_id` VARCHAR(255) DEFAULT NULL COMMENT '账户ID',
  `title` VARCHAR(255) DEFAULT NULL COMMENT '标题',
  `business_type` VARCHAR(255) DEFAULT NULL COMMENT '交易类型',
  `method` VARCHAR(255) DEFAULT NULL COMMENT '方法',
  `request_method` VARCHAR(255) DEFAULT NULL COMMENT '请求方法',
  `operator_type` VARCHAR(255) DEFAULT NULL COMMENT '操作类型',
  `oper_name` VARCHAR(255) DEFAULT NULL COMMENT '操作员',
  `oper_url` VARCHAR(255) DEFAULT NULL COMMENT '操作路径',
  `oper_ip` VARCHAR(255) DEFAULT NULL COMMENT '操作IP',
  `oper_location` VARCHAR(255) DEFAULT NULL COMMENT '操作地址',
  `oper_param` VARCHAR(255) DEFAULT NULL COMMENT '操作参数',
  `error_message` VARCHAR(255) DEFAULT NULL COMMENT '错误信息',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='云账户审核实体类';


CREATE TABLE `cloud_content` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `content_type_value` VARCHAR(255) DEFAULT NULL COMMENT '内容类型',
  `title` VARCHAR(255) DEFAULT NULL COMMENT '标题',
  `content_desc` VARCHAR(255) DEFAULT NULL COMMENT '内容描述',
  `banner` VARCHAR(255) DEFAULT NULL COMMENT '背景图片',
  `banner_desc` VARCHAR(255) DEFAULT NULL COMMENT '图片描述',
  `view_count` INT DEFAULT NULL COMMENT '查看次数',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云内容的实体类';


CREATE TABLE `cloud_document` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `document_type` VARCHAR(255) DEFAULT NULL COMMENT '文档类型',
  `link_name` VARCHAR(255) DEFAULT NULL COMMENT '链接名称',
  `link_path` VARCHAR(255) DEFAULT NULL COMMENT '链接地址',
  `link_logo` VARCHAR(255) DEFAULT NULL COMMENT '链接图标',
  `link_desc` VARCHAR(255) DEFAULT NULL COMMENT '链接描述',
  `link_target` VARCHAR(255) DEFAULT NULL COMMENT '链接打开状态',
  `link_design` VARCHAR(255) DEFAULT NULL COMMENT '链接状态',
  `link_sort` INT DEFAULT NULL COMMENT '链接排序',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云文档的实体类';


CREATE TABLE `cloud_feedback` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `type_code` VARCHAR(255) DEFAULT NULL COMMENT '建议类型',
  `title` VARCHAR(255) DEFAULT NULL COMMENT '标题',
  `problem_desc` VARCHAR(255) DEFAULT NULL COMMENT '问题描述',
  `proposed_solution` VARCHAR(255) DEFAULT NULL COMMENT '建议方案',
  `product_item_id` VARCHAR(255) DEFAULT NULL COMMENT '关联产品',
  `account_id` VARCHAR(255) DEFAULT NULL COMMENT '账户名',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云反馈的实体类';


CREATE TABLE `cloud_link_path` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `link_type` VARCHAR(255) DEFAULT NULL COMMENT '链接类型',
  `link_name` VARCHAR(255) DEFAULT NULL COMMENT '链接名称',
  `link_path` VARCHAR(255) DEFAULT NULL COMMENT '链接地址',
  `link_desc` VARCHAR(255) DEFAULT NULL COMMENT '链接描述',
  `link_target` VARCHAR(255) DEFAULT NULL COMMENT '链接打开状态',
  `link_design` VARCHAR(255) DEFAULT NULL COMMENT '链接状态',
  `link_sort` INT DEFAULT NULL COMMENT '链接排序',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云链接路径的实体类';


CREATE TABLE `cloud_partner` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `partner_type` VARCHAR(255) DEFAULT NULL COMMENT '合作伙伴类型',
  `logo` VARCHAR(255) DEFAULT NULL COMMENT '公司logo',
  `company_name` VARCHAR(255) DEFAULT NULL COMMENT '公司名称',
  `company_tel` VARCHAR(255) DEFAULT NULL COMMENT '联系电话',
  `company_email` VARCHAR(255) DEFAULT NULL COMMENT '联系邮箱',
  `company_address` VARCHAR(255) DEFAULT NULL COMMENT '公司地址',
  `company_desc` VARCHAR(255) DEFAULT NULL COMMENT '公司简介',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云合作伙伴信息的实体类';


CREATE TABLE `cloud_product_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `account_id` VARCHAR(255) DEFAULT NULL COMMENT '账户id',
  `product_item_id` VARCHAR(255) DEFAULT NULL COMMENT '产品id',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云产品账户信息的实体类';


CREATE TABLE `cloud_product_apply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `account_name` VARCHAR(255) DEFAULT NULL COMMENT '用户名',
  `account_id` VARCHAR(255) DEFAULT NULL COMMENT '账户id',
  `product_item_id` VARCHAR(255) DEFAULT NULL COMMENT '产品id',
  `apply_status` INT DEFAULT NULL COMMENT '申请状态(0未审核|1已审核|2不通过|3通过)',
  `apply_reason` VARCHAR(255) DEFAULT NULL COMMENT '申请原因',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云产品申请信息的实体类';


CREATE TABLE `cloud_product_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(255) DEFAULT NULL COMMENT '产品名称',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `product_brief` VARCHAR(255) DEFAULT NULL COMMENT '产品简介',
  `product_describe` VARCHAR(255) DEFAULT NULL COMMENT '产品描述',
  `sub_name` VARCHAR(255) DEFAULT NULL COMMENT '副标题',
  `banner` VARCHAR(255) DEFAULT NULL COMMENT '背景图',
  `short_name` VARCHAR(255) DEFAULT NULL COMMENT '简称',
  `view_count` INT DEFAULT NULL COMMENT '查看次数',
  `link_path` VARCHAR(255) DEFAULT NULL COMMENT '产品链接',
  `item_status` VARCHAR(255) DEFAULT NULL COMMENT '当前状态(规划planning|研究research|生产production)',
  `prod_status` VARCHAR(255) DEFAULT NULL COMMENT '产品状态(正常normal|内测internal|公测public)',
  `identity_status` VARCHAR(255) DEFAULT NULL COMMENT '标识状态(0启用|1禁用)',
  `product_type_id` VARCHAR(255) DEFAULT NULL COMMENT '所属类型id',
  `has_recommend` INT DEFAULT NULL COMMENT '是否推荐',
  `has_inner` INT DEFAULT NULL COMMENT '是否内置链接(内置1|正常0)',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云产品项信息的实体类';


CREATE TABLE `cloud_product_label` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `title` VARCHAR(255) DEFAULT NULL COMMENT '标题',
  `label_type` VARCHAR(255) DEFAULT NULL COMMENT '类型(business业务|advantage优势|case案例)',
  `label_describe` VARCHAR(255) DEFAULT NULL COMMENT '描述',
  `banner` VARCHAR(255) DEFAULT NULL COMMENT '背景图',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `details_desc` VARCHAR(255) DEFAULT NULL COMMENT '详情简介',
  `details_title` VARCHAR(255) DEFAULT NULL COMMENT '详情标题',
  `details_describe` VARCHAR(255) DEFAULT NULL COMMENT '详情描述',
  `product_item_id` VARCHAR(255) DEFAULT NULL COMMENT '所属产品id',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用于存储云产品标签信息的实体类';


CREATE TABLE `cloud_product_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(255) DEFAULT NULL COMMENT '名称',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `banner` VARCHAR(255) DEFAULT NULL COMMENT '背景图',
  `parent_id` VARCHAR(255) DEFAULT NULL COMMENT '父类id',
  `sub_name` VARCHAR(255) DEFAULT NULL COMMENT '子名称',
  `type_describe` VARCHAR(255) DEFAULT NULL COMMENT '产品类型描述',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品类型实体类';


CREATE TABLE `service_ask` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `service_type_id` VARCHAR(255) DEFAULT NULL COMMENT '留言类型',
  `creator_id` VARCHAR(255) DEFAULT NULL COMMENT '创建者',
  `replyer_id` VARCHAR(255) DEFAULT NULL COMMENT '回复者',
  `ask_title` VARCHAR(255) DEFAULT NULL COMMENT '咨询标题',
  `ask_text` VARCHAR(255) DEFAULT NULL COMMENT '咨询内容',
  `creation_date` DATETIME COMMENT '咨询日期',
  `creation_ip` VARCHAR(255) DEFAULT NULL COMMENT '咨询IP',
  `creation_area` VARCHAR(255) DEFAULT NULL COMMENT '咨询地区',
  `reply_text` VARCHAR(255) DEFAULT NULL COMMENT '回复内容',
  `reply_date` DATETIME COMMENT '回复日期',
  `reply_ip` VARCHAR(255) DEFAULT NULL COMMENT '回复IP',
  `reply_area` VARCHAR(255) DEFAULT NULL COMMENT '回复地区',
  `is_reply` VARCHAR(255) DEFAULT NULL COMMENT '是否回复',
  `is_recommend` VARCHAR(255) DEFAULT NULL COMMENT '是否推荐',
  `guestbook_status` INT DEFAULT NULL COMMENT '咨询状态(0：已审核|1：未审核|2：屏蔽)',
  `username` VARCHAR(255) DEFAULT NULL COMMENT '用户名',
  `creation_gender` VARCHAR(255) DEFAULT NULL COMMENT '性别',
  `creation_phone` VARCHAR(255) DEFAULT NULL COMMENT '电话',
  `creation_mobile` VARCHAR(255) DEFAULT NULL COMMENT '手机',
  `creation_qq` VARCHAR(255) DEFAULT NULL COMMENT 'QQ号码',
  `creation_email` VARCHAR(255) DEFAULT NULL COMMENT '电子邮箱',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='云服务咨询实体类';


CREATE TABLE `cloud_service_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `service_type_name` VARCHAR(255) DEFAULT NULL COMMENT '名称',
  `service_type_number` VARCHAR(255) DEFAULT NULL COMMENT '编码',
  `service_type_seq` INT DEFAULT NULL COMMENT '排序',
  `service_type_desc` VARCHAR(255) DEFAULT NULL COMMENT '描述',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务类型实体类';


CREATE TABLE `cloud_solution_label` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `title` VARCHAR(255) DEFAULT NULL COMMENT '标题',
  `label_type` VARCHAR(255) DEFAULT NULL COMMENT '类型(business业务|advantage优势|case案例)',
  `label_describe` VARCHAR(255) DEFAULT NULL COMMENT '描述',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `solution_article_id` VARCHAR(255) DEFAULT NULL COMMENT '所属解决方案id',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='解决方案标签实体类';


CREATE TABLE `cloud_solution_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(255) DEFAULT NULL COMMENT '名称',
  `label_describe` VARCHAR(255) DEFAULT NULL COMMENT '描述',
  `banner` VARCHAR(255) DEFAULT NULL COMMENT '背景图',
  `sort_number` INT DEFAULT NULL COMMENT '排序',
  `parent_id` VARCHAR(255) DEFAULT NULL COMMENT '父类id',
  `sub_name` VARCHAR(255) DEFAULT NULL COMMENT '子名称',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `ProductItem_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `ProductItem_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的ProductItem.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='解决方案类型实体类';
